name: Build LaTeX PDF

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Install LaTeX
      run: sudo apt-get update && sudo apt-get install -y texlive-full

    - name: Build PDF
      run: latexmk -pdf -interaction=nonstopmode My CV.tex

    - name: Upload PDF artifact
      uses: actions/upload-artifact@v3
      with:
        name: compiled-pdf
        path: your-file.pdf
