name: Build LaTeX PDF

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: danteev/texlive  # Pre-built Docker image with LaTeX pre-installed

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Build PDF
      run: latexmk -pdf -interaction=nonstopmode My_CV.tex

    - name: Upload PDF artifact
      uses: actions/upload-artifact@v3
      with:
        name: compiled-pdf
        path: .docs/My_CV.pdf
